version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true
    optional: true

tasks:
  check:
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: default
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: print
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: cli
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: prompt
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: prompt-password
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: prompt,cli
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: prompt-password,cli
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: cli,coroutine
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: fs
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: process
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: parse
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: json,yaml,toml
    - task: cargo:clippy-package-feature
      vars:
        PACKAGE: pistonite-cu
        FEATURES: full
    - task: cargo:fmt-check
    - cmd: echo "checking default feature"; (grep "^default = \[\]$" Cargo.toml || rg "^default = \[\]$" Cargo.toml)

  fix:
    - task: cargo:fmt-fix


  test:
    - cargo test 
    - cargo test --features cli
    - cargo test --features full

  publish:
    - cmd: cargo publish
      ignore_error: true
