version: '3'

includes:
  common:
    taskfile: ./mono-dev/task/common.yaml
    flatten: true
    optional: true

  cargo:
    taskfile: ./mono-dev/task/cargo.yaml
    optional: true
    internal: true

  cu:             {taskfile: ./packages/copper,             dir: ./packages/copper,             internal: true}
  cu-proc-macros: {taskfile: ./packages/copper-proc-macros, dir: ./packages/copper-proc-macros, internal: true}
  pm:             {taskfile: ./packages/promethium,         dir: ./packages/promethium,         internal: true}
  terminal-tests: {taskfile: ./packages/terminal-tests,     dir: ./packages/terminal-tests,     internal: true}

tasks:
  install-cargo-extra-tools:
    desc: Install or upgrade extra tools needed for development using cargo onto the system
    aliases: [icets]
    cmds:
      - task: cargo-binstall
        vars:
          PACKAGES: shwoop

  install:
    desc: Install or sync project dependencies
    cmds:
      - rm -rf mono-dev
      - git clone https://github.com/Pistonight/mono-dev --depth 1

  check:
    desc: Run linters to check the code
    cmds:
      - task: pm:check
      - task: cu-proc-macros:check
      - task: cu:check
      - task: terminal-tests:check

  fix:
    desc: Fix style issues
    cmds:
      - task: pm:fix
      - task: cu-proc-macros:fix
      - task: cu:fix
      - task: terminal-tests:fix

  test:
    desc: Run tests
    cmds:
      - task: pm:test
      - task: cu:test
      - task: terminal-tests:run

  dev-doc:
    desc: Watch and serve documentation
    cmds:
      - task: cargo:watch-serve-doc
        vars:
          SHWOOP_ARGS: -w packages
          CARGO_ARGS: --features full,nightly
          TOOLCHAIN: +nightly

  doc-ci:
    desc: (CI Only) Build documentation
    cmds:
      # note: require nightly toolchain in CI
      - cargo doc --no-deps --features full,nightly -p pistonite-cu -p pistonite-cu-proc-macros -p pistonite-pm
      - cmd: >
          echo "Generating index redirect";
          echo "<!DOCTYPE html>" > target/doc/index.html;
          echo "<html><head>" >> target/doc/index.html;
          echo '<meta http-equiv="refresh" content="0;url=https://cu.pistonite.dev/pistonite_cu/">' >> target/doc/index.html;
          echo "</head><body></body></html>" >> target/doc/index.html;
        silent: true

  publish:
    desc: Publish a release
    cmds:
      # order matters
      - task: pm:publish
      - task: cu-proc-macros:publish
      - task: cu:publish

  upgrade:
    desc: Upgrade tools and/or dependencies
    cmds:
      - cargo upgrade
