version: '3'

includes:
  common:
    taskfile: ./packages/mono-dev/task/common.yaml
    flatten: true
    optional: true

  cargo:
    taskfile: ./packages/mono-dev/task/cargo.yaml
    optional: true
    internal: true

  cu:             {taskfile: ./packages/copper,             dir: ./packages/copper,             internal: true}
  cu-proc-macros: {taskfile: ./packages/copper-proc-macros, dir: ./packages/copper-proc-macros, internal: true}
  pm:             {taskfile: ./packages/promethium,         dir: ./packages/promethium,         internal: true}

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: cargo-binstall
        vars:
          PACKAGES: cargo-watch live-server

  install:
    cmds:
      - task: setup-mono-dev-at-packages

  check:
    cmds:
      - task: pm:check
      - task: cu-proc-macros:check
      - task: cu:check

  test:
    cmds:
      - task: cu:test

  dev-doc:
    cmds:
      - task: cargo:watch-serve-doc
        vars:
          CARGO_ARGS: --features full,nightly
          TOOLCHAIN: +nightly

  doc:
    cmds:
      # note: require nightly toolchain in CI
      - cargo doc --no-deps --features full,nightly
      - cmd: >
          echo "Generating index redirect";
          echo "<!DOCTYPE html>" > target/doc/index.html;
          echo "<html><head>" >> target/doc/index.html;
          echo '<meta http-equiv="refresh" content="0;url=https://cu.pistonite.dev/pistonite-cu/">' >> target/doc/index.html;
          echo "</head><body></body></html>" >> target/doc/index.html;
        silent: true

  publish:
    cmds:
      # order matters
      - task: pm:publish
      - task: cu-proc-macros:publish
      - task: cu:publish
