version: '3'

includes:
  cargo:
    taskfile: ../../mono-dev/task/cargo.yaml
    internal: true
    optional: true

tasks:
  run:
    desc: Run terminal tests
    cmds:
      - cargo run --features bin -- {{.CLI_ARGS}}
  check:
    desc: Run linters to check the code
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check
  fix:
    desc: Fix style issues
    cmds:
      - task: cargo:fmt-fix
