version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true
    optional: true

tasks:
  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check
  fix:
    - task: cargo:fmt-fix
  publish:
    - cmd: cargo publish
      ignore_error: true
  test:
    - cargo test
    - cargo test --features full
    - cargo test --no-default-features --features full
