version: '3'

includes:
  cargo:
    taskfile: ../mono-dev/task/cargo.yaml
    internal: true
tasks:
  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check
  fix:
    cmds:
      - task: cargo:fmt-fix
  publish:
    cmds:
      - cmd: cargo publish
        ignore_error: true
